from enum import Enum


class StepName(str, Enum):
    DATA_READING = "DATA_READING"
    DATA_PREPROCESSING = "DATA_PREPROCESSING"
    BLOCK_BUILDING = "BLOCK_BUILDING"
    FIELD_AND_RECORD_COMPARISON = "FIELD_AND_RECORD_COMPARISON"
    CLASSIFICATION = "CLASSIFICATION"
    EVALUATION = "EVALUATION"
